<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>About WebAir</title>
    <link type="text/css" href="styles/main.css" rel="stylesheet" />
    <link type="text/css" href="styles/nav.css" rel="stylesheet" />
    
	<style>
		/* I'm sorry. */
		#maincontent {
			margin-top:-7px;
		}
	</style>
</head>

<body>
	<div id="contall"> 
    	<div id="mainheader">
        	<div id="mainlogo">
            	<a href="index.php"><h1>flywebair.com</h1></a>
			</div><!--mainlogo-->
            <div id="mainnav">
        	<ul>
				<li class="home"><a href="index.php">Home</a></li>
				<li class="about"><a href="about.php">About</a></li>
				<li class="book"><a href="book.php">Book</a></li>
				<li class="login"><a href="login.php">Login</a></li>
			</ul>
            </div><!--mainnav-->
        </div> <!--mainheader-->
        
        <div id="maincontent">
            
			<h2>About us</h2>
            <div class="mainbox">
            	<h3 id="about">About us</h3>
                <p>flyWebAir.com are headquartered at Bristol International Airport. We carry more passengers than any other Bristol-based airline, operating domestic over 5 routes between 5 cities in the UK and Ireland. As of 30 September 2011 we employed over 9,000 people, based throughout Europe but mainly in the UK.</p>
                <p>We have seen rapid expansion since our establishment in 1995, having grown through a combination of acquisitions and base openings fuelled by consumer demand for low-cost air travel. The airline, along with franchise airline flyAirWeb, now operates less than or equal to 1 aircraft, an Airbus A319. We carried 4.2 million passengers and we are the third-largest low-cost carrier in Europe, behind Ryanair & Easyjet.</p>
                <p>flyWebAir was featured in Aeroplane series broadcast on Channel 4 which followed the airline's operations at Bristol International and later at other bases. Our's founder, Sir Tyrone Revel, was featured heavily in the series.</p>
				<h3 id="history">Our history</h3>
                <p>WebAir was established in 1995. It was launched by African-American businessman Tyrone Revel with two wet leased Boeing 737-200 aircraft, initially operating two routes: London Luton to Glasgow and Edinburgh. In April 1996, the first wholly-owned aircraft was delivered to WebAir, enabling its first international route, to Amsterdam. Until October 1997, the aircraft were operated by GB Airways, and subsequently by Air Foyle as WebAir had not yet received its Air Operator's Certificate.
</p>
                <h3 id="green">Green policy</h3>
                <p>We have an environmental code, based on three promises.</p>
                <p>1: Efficient use of aircraft<br />
				WebAir's straight-forward pricing model means that we attract more people to fly with us - and because we have configured the seating of our planes to welcome more passengers per aircraft, our traditional rivals use 27% more fuel than us on the same plane type and same route.</p>
                <p>WebAir has invested £7 billion in the latest technology to make sure that we operate one of the cleanest, youngest and most fuel efficient fleets in the industry - the average age of our aircraft is 2.3 years. This minimises our environmental impact - and passengers enjoy a modern, spanking new plane!</p>
                
                <p>2: Efficient ground operations<br />
                Getting our planes emptied, cleaned, checked, refuelled and boarded with passengers and luggage as quickly as possible means we need less airport services than other airlines, so we use less energy on the ground. It also means our planes can be more efficient, as well as requiring fewer gates and other airport infrastructure than full-service carriers.
                </p>
                <p>Quicker turnarounds and greater efficiency requires less ground equipment. We avoid using air bridges and motorised steps wherever possible. Our cabin crew clean the aircraft interior and doesn't require a separate cleaning crew.</p>

				<p>3: Our offset scheme achieves the highest quality standards.<br />
                <ul>
                <li>Our offset calculations are based on actual emissions generated by actual flights</li>
                <li>We only support UN approved Certified Emission Reduction schemes - each credit of carbon represents a true reduction in carbon</li>
                <li>We are transparent - detailing how much goes to the project with no extortionate agency fees</li>
                <li>Credits will be retired on behalf of the customers</li>
                <li>webair works out your share of the carbon emitted from your flight</li>
                <li>webair buys an equivalent share in a UN certified emission reduction project. There is no middle-man in webair's not-for-profit scheme</li>
                <li>Where the money goes</li>
                <li>webair buys from a range of UN Certified Emission Reduction projects (CERs). Why? They are the highest quality carbon credits available, where the UN Board of Approval verifies the emission saving from the project - so the carbon reduction is real. The projects range from bio-mass projects to wind farms, (see project example below) the common thread is the UN stamp of approval. We retire the credits, putting them beyond use.</li>
                </ul>




                <h3 id="terms">Terms and conditions</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed convallis, ante et venenatis scelerisque, diam nibh porttitor lacus, non tincidunt massa elit quis dolor. Integer in erat molestie turpis bibendum porttitor. Phasellus nulla risus, auctor vitae pellentesque a, blandit id est. Maecenas adipiscing neque eget ipsum imperdiet in tempor ante. </p>
			</div><!--mainbox-->
                
            
        </div><!--maincontent-->
        
		<div id="sidecontent">
            <h2>Navigation</h2>
        	<div class="altbox">
				<ul>
                	<li><a href="#about">About us</a></li>
                	<li><a href="#history">Our history</a></li>
                    <li><a href="#green">Green policy</a></li>
                    <li><a href="#terms">Terms and conditions</a></li>
				</ul>            	                
            </div><!--altbox-->
            
            <div class="advert">
            	<img src="images/ads/sidead1.jpg">
            </div><!--advert-->
            
        </div><!--sidecontent-->
        

	</div><!--contall-->
            <div id="mainfooter">
        <p><a href="">about us</a> | <a href="">contact us</a> | <a href="">terms and conditions</a></p>
        </div><!--mainfooter-->
</body>
</html>
